# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scada_ekran_4.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1915, 1000)
        MainWindow.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(180, 30, 1771, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uretim_menu = QtWidgets.QPushButton(self.layoutWidget)
        self.uretim_menu.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.uretim_menu.setFont(font)
        self.uretim_menu.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.uretim_menu.setObjectName("uretim_menu")
        self.horizontalLayout.addWidget(self.uretim_menu)
        self.manuel_menu = QtWidgets.QPushButton(self.layoutWidget)
        self.manuel_menu.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.manuel_menu.setFont(font)
        self.manuel_menu.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.manuel_menu.setObjectName("manuel_menu")
        self.horizontalLayout.addWidget(self.manuel_menu)
        self.ayarlar_menu = QtWidgets.QPushButton(self.layoutWidget)
        self.ayarlar_menu.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ayarlar_menu.setFont(font)
        self.ayarlar_menu.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.ayarlar_menu.setObjectName("ayarlar_menu")
        self.horizontalLayout.addWidget(self.ayarlar_menu)
        self.kalibrasyon_menu = QtWidgets.QPushButton(self.layoutWidget)
        self.kalibrasyon_menu.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.kalibrasyon_menu.setFont(font)
        self.kalibrasyon_menu.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.kalibrasyon_menu.setObjectName("kalibrasyon_menu")
        self.horizontalLayout.addWidget(self.kalibrasyon_menu)
        self.recete_menu = QtWidgets.QPushButton(self.layoutWidget)
        self.recete_menu.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.recete_menu.setFont(font)
        self.recete_menu.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.recete_menu.setObjectName("recete_menu")
        self.horizontalLayout.addWidget(self.recete_menu)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 99, 1915, 891))
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"background-color: rgb(204, 195, 204);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.uretim_sayfasi = QtWidgets.QWidget()
        self.uretim_sayfasi.setObjectName("uretim_sayfasi")
        self.tesis_resim = QtWidgets.QLabel(self.uretim_sayfasi)
        self.tesis_resim.setGeometry(QtCore.QRect(0, 0, 1915, 891))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.tesis_resim.setFont(font)
        self.tesis_resim.setAutoFillBackground(False)
        self.tesis_resim.setStyleSheet("\n"
"border-image: url(:/background/ana montaj.PNG);")
        self.tesis_resim.setText("")
        self.tesis_resim.setScaledContents(True)
        self.tesis_resim.setWordWrap(False)
        self.tesis_resim.setObjectName("tesis_resim")
        self.proses_baslat_button = QtWidgets.QPushButton(self.uretim_sayfasi)
        self.proses_baslat_button.setGeometry(QtCore.QRect(1600, 110, 261, 81))
        self.proses_baslat_button.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.proses_baslat_button.setFont(font)
        self.proses_baslat_button.setObjectName("proses_baslat_button")
        self.acil_stop_button = QtWidgets.QPushButton(self.uretim_sayfasi)
        self.acil_stop_button.setGeometry(QtCore.QRect(1600, 220, 261, 81))
        self.acil_stop_button.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.acil_stop_button.setFont(font)
        self.acil_stop_button.setObjectName("acil_stop_button")
        self.mikser_manuel_bosalt_button = QtWidgets.QPushButton(self.uretim_sayfasi)
        self.mikser_manuel_bosalt_button.setGeometry(QtCore.QRect(1600, 330, 261, 81))
        self.mikser_manuel_bosalt_button.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.mikser_manuel_bosalt_button.setFont(font)
        self.mikser_manuel_bosalt_button.setObjectName("mikser_manuel_bosalt_button")
        self.cimento_tartim_bosalt = QtWidgets.QPushButton(self.uretim_sayfasi)
        self.cimento_tartim_bosalt.setGeometry(QtCore.QRect(1350, 170, 201, 61))
        self.cimento_tartim_bosalt.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cimento_tartim_bosalt.setFont(font)
        self.cimento_tartim_bosalt.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"background-color: rgb(255, 41, 69);")
        self.cimento_tartim_bosalt.setObjectName("cimento_tartim_bosalt")
        self.katki_tartim_bosalt = QtWidgets.QPushButton(self.uretim_sayfasi)
        self.katki_tartim_bosalt.setGeometry(QtCore.QRect(1110, 20, 201, 61))
        self.katki_tartim_bosalt.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.katki_tartim_bosalt.setFont(font)
        self.katki_tartim_bosalt.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"background-color: rgb(255, 41, 69);")
        self.katki_tartim_bosalt.setObjectName("katki_tartim_bosalt")
        self.su_tartim_bosalt = QtWidgets.QPushButton(self.uretim_sayfasi)
        self.su_tartim_bosalt.setGeometry(QtCore.QRect(540, 20, 201, 61))
        self.su_tartim_bosalt.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.su_tartim_bosalt.setFont(font)
        self.su_tartim_bosalt.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"background-color: rgb(255, 41, 69);")
        self.su_tartim_bosalt.setObjectName("su_tartim_bosalt")
        self.tartim_bandi_bosalt = QtWidgets.QPushButton(self.uretim_sayfasi)
        self.tartim_bandi_bosalt.setGeometry(QtCore.QRect(170, 430, 201, 61))
        self.tartim_bandi_bosalt.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tartim_bandi_bosalt.setFont(font)
        self.tartim_bandi_bosalt.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"background-color: rgb(255, 41, 69);")
        self.tartim_bandi_bosalt.setObjectName("tartim_bandi_bosalt")
        self.frame_3 = QtWidgets.QFrame(self.uretim_sayfasi)
        self.frame_3.setGeometry(QtCore.QRect(30, 730, 851, 111))
        self.frame_3.setStyleSheet("background-color: rgb(192, 201, 212);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_3)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 10, 831, 91))
        self.tableWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_2.setRowCount(1)
        self.tableWidget_2.setColumnCount(7)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.lb_recete_baslik_2 = QtWidgets.QLabel(self.uretim_sayfasi)
        self.lb_recete_baslik_2.setGeometry(QtCore.QRect(330, 690, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lb_recete_baslik_2.setFont(font)
        self.lb_recete_baslik_2.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_recete_baslik_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_recete_baslik_2.setObjectName("lb_recete_baslik_2")
        self.mikser_bosaltma_piston_g = QtWidgets.QLabel(self.uretim_sayfasi)
        self.mikser_bosaltma_piston_g.setGeometry(QtCore.QRect(820, 530, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mikser_bosaltma_piston_g.setFont(font)
        self.mikser_bosaltma_piston_g.setAlignment(QtCore.Qt.AlignCenter)
        self.mikser_bosaltma_piston_g.setObjectName("mikser_bosaltma_piston_g")
        self.kum_1_vibro_g = QtWidgets.QLabel(self.uretim_sayfasi)
        self.kum_1_vibro_g.setGeometry(QtCore.QRect(110, 180, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kum_1_vibro_g.setFont(font)
        self.kum_1_vibro_g.setAlignment(QtCore.Qt.AlignCenter)
        self.kum_1_vibro_g.setObjectName("kum_1_vibro_g")
        self.kum_2_vibro_g = QtWidgets.QLabel(self.uretim_sayfasi)
        self.kum_2_vibro_g.setGeometry(QtCore.QRect(220, 180, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kum_2_vibro_g.setFont(font)
        self.kum_2_vibro_g.setAlignment(QtCore.Qt.AlignCenter)
        self.kum_2_vibro_g.setObjectName("kum_2_vibro_g")
        self.kum_3_vibro_g = QtWidgets.QLabel(self.uretim_sayfasi)
        self.kum_3_vibro_g.setGeometry(QtCore.QRect(330, 180, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kum_3_vibro_g.setFont(font)
        self.kum_3_vibro_g.setAlignment(QtCore.Qt.AlignCenter)
        self.kum_3_vibro_g.setObjectName("kum_3_vibro_g")
        self.tartim_bandi_motor_g = QtWidgets.QLabel(self.uretim_sayfasi)
        self.tartim_bandi_motor_g.setGeometry(QtCore.QRect(10, 390, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tartim_bandi_motor_g.setFont(font)
        self.tartim_bandi_motor_g.setAlignment(QtCore.Qt.AlignCenter)
        self.tartim_bandi_motor_g.setObjectName("tartim_bandi_motor_g")
        self.tartim_bandi_akt_mt_g = QtWidgets.QLabel(self.uretim_sayfasi)
        self.tartim_bandi_akt_mt_g.setGeometry(QtCore.QRect(430, 460, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tartim_bandi_akt_mt_g.setFont(font)
        self.tartim_bandi_akt_mt_g.setAlignment(QtCore.Qt.AlignCenter)
        self.tartim_bandi_akt_mt_g.setObjectName("tartim_bandi_akt_mt_g")
        self.kum_3_piston_g = QtWidgets.QLabel(self.uretim_sayfasi)
        self.kum_3_piston_g.setGeometry(QtCore.QRect(330, 130, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kum_3_piston_g.setFont(font)
        self.kum_3_piston_g.setAlignment(QtCore.Qt.AlignCenter)
        self.kum_3_piston_g.setObjectName("kum_3_piston_g")
        self.kum_1_piston_g = QtWidgets.QLabel(self.uretim_sayfasi)
        self.kum_1_piston_g.setGeometry(QtCore.QRect(110, 130, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kum_1_piston_g.setFont(font)
        self.kum_1_piston_g.setAlignment(QtCore.Qt.AlignCenter)
        self.kum_1_piston_g.setObjectName("kum_1_piston_g")
        self.kum_2_piston_g = QtWidgets.QLabel(self.uretim_sayfasi)
        self.kum_2_piston_g.setGeometry(QtCore.QRect(220, 130, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kum_2_piston_g.setFont(font)
        self.kum_2_piston_g.setAlignment(QtCore.Qt.AlignCenter)
        self.kum_2_piston_g.setObjectName("kum_2_piston_g")
        self.su_pompasi_g = QtWidgets.QLabel(self.uretim_sayfasi)
        self.su_pompasi_g.setGeometry(QtCore.QRect(690, 150, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.su_pompasi_g.setFont(font)
        self.su_pompasi_g.setAlignment(QtCore.Qt.AlignCenter)
        self.su_pompasi_g.setObjectName("su_pompasi_g")
        self.katki_pompasi_g = QtWidgets.QLabel(self.uretim_sayfasi)
        self.katki_pompasi_g.setGeometry(QtCore.QRect(1080, 140, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.katki_pompasi_g.setFont(font)
        self.katki_pompasi_g.setAlignment(QtCore.Qt.AlignCenter)
        self.katki_pompasi_g.setObjectName("katki_pompasi_g")
        self.cimento_akt_hlz_mt_g = QtWidgets.QLabel(self.uretim_sayfasi)
        self.cimento_akt_hlz_mt_g.setGeometry(QtCore.QRect(1190, 410, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cimento_akt_hlz_mt_g.setFont(font)
        self.cimento_akt_hlz_mt_g.setAlignment(QtCore.Qt.AlignCenter)
        self.cimento_akt_hlz_mt_g.setObjectName("cimento_akt_hlz_mt_g")
        self.mikser_motoru_g = QtWidgets.QLabel(self.uretim_sayfasi)
        self.mikser_motoru_g.setGeometry(QtCore.QRect(760, 380, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mikser_motoru_g.setFont(font)
        self.mikser_motoru_g.setAlignment(QtCore.Qt.AlignCenter)
        self.mikser_motoru_g.setObjectName("mikser_motoru_g")
        self.lineEdit = QtWidgets.QLineEdit(self.uretim_sayfasi)
        self.lineEdit.setGeometry(QtCore.QRect(870, 300, 61, 20))
        self.lineEdit.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.uretim_sayfasi)
        self.lineEdit_2.setGeometry(QtCore.QRect(1080, 300, 61, 20))
        self.lineEdit_2.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.uretim_sayfasi)
        self.lineEdit_3.setGeometry(QtCore.QRect(1000, 170, 61, 20))
        self.lineEdit_3.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.mikser_bosaltma_vibro_g = QtWidgets.QLabel(self.uretim_sayfasi)
        self.mikser_bosaltma_vibro_g.setGeometry(QtCore.QRect(1080, 530, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mikser_bosaltma_vibro_g.setFont(font)
        self.mikser_bosaltma_vibro_g.setAlignment(QtCore.Qt.AlignCenter)
        self.mikser_bosaltma_vibro_g.setObjectName("mikser_bosaltma_vibro_g")
        self.stackedWidget.addWidget(self.uretim_sayfasi)
        self.manuel_sayfasi = QtWidgets.QWidget()
        self.manuel_sayfasi.setObjectName("manuel_sayfasi")
        self.layoutWidget1 = QtWidgets.QWidget(self.manuel_sayfasi)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 120, 1911, 741))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.HDRLK_MTR_Y = QtWidgets.QPushButton(self.layoutWidget1)
        self.HDRLK_MTR_Y.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.HDRLK_MTR_Y.setFont(font)
        self.HDRLK_MTR_Y.setObjectName("HDRLK_MTR_Y")
        self.gridLayout.addWidget(self.HDRLK_MTR_Y, 2, 0, 1, 1)
        self.SRN_Y = QtWidgets.QPushButton(self.layoutWidget1)
        self.SRN_Y.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.SRN_Y.setFont(font)
        self.SRN_Y.setObjectName("SRN_Y")
        self.gridLayout.addWidget(self.SRN_Y, 1, 3, 1, 1)
        self.BNKR_VBR_1_Y = QtWidgets.QPushButton(self.layoutWidget1)
        self.BNKR_VBR_1_Y.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BNKR_VBR_1_Y.setFont(font)
        self.BNKR_VBR_1_Y.setObjectName("BNKR_VBR_1_Y")
        self.gridLayout.addWidget(self.BNKR_VBR_1_Y, 1, 2, 1, 1)
        self.KTK_PMP_2_Y = QtWidgets.QPushButton(self.layoutWidget1)
        self.KTK_PMP_2_Y.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.KTK_PMP_2_Y.setFont(font)
        self.KTK_PMP_2_Y.setAutoDefault(False)
        self.KTK_PMP_2_Y.setDefault(False)
        self.KTK_PMP_2_Y.setFlat(False)
        self.KTK_PMP_2_Y.setObjectName("KTK_PMP_2_Y")
        self.gridLayout.addWidget(self.KTK_PMP_2_Y, 2, 1, 1, 1)
        self.BNKR_PSTN_2_Y = QtWidgets.QPushButton(self.layoutWidget1)
        self.BNKR_PSTN_2_Y.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BNKR_PSTN_2_Y.setFont(font)
        self.BNKR_PSTN_2_Y.setObjectName("BNKR_PSTN_2_Y")
        self.gridLayout.addWidget(self.BNKR_PSTN_2_Y, 2, 2, 1, 1)
        self.TRTM_VBR_Y = QtWidgets.QPushButton(self.layoutWidget1)
        self.TRTM_VBR_Y.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TRTM_VBR_Y.setFont(font)
        self.TRTM_VBR_Y.setObjectName("TRTM_VBR_Y")
        self.gridLayout.addWidget(self.TRTM_VBR_Y, 1, 0, 1, 1)
        self.KTK_PMP_1_Y = QtWidgets.QPushButton(self.layoutWidget1)
        self.KTK_PMP_1_Y.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.KTK_PMP_1_Y.setFont(font)
        self.KTK_PMP_1_Y.setAutoDefault(False)
        self.KTK_PMP_1_Y.setDefault(False)
        self.KTK_PMP_1_Y.setFlat(False)
        self.KTK_PMP_1_Y.setObjectName("KTK_PMP_1_Y")
        self.gridLayout.addWidget(self.KTK_PMP_1_Y, 1, 1, 1, 1)
        self.BNKR_VBR_3_Y = QtWidgets.QPushButton(self.layoutWidget1)
        self.BNKR_VBR_3_Y.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BNKR_VBR_3_Y.setFont(font)
        self.BNKR_VBR_3_Y.setObjectName("BNKR_VBR_3_Y")
        self.gridLayout.addWidget(self.BNKR_VBR_3_Y, 0, 3, 1, 1)
        self.BNKR_PSTN_1_Y = QtWidgets.QPushButton(self.layoutWidget1)
        self.BNKR_PSTN_1_Y.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BNKR_PSTN_1_Y.setFont(font)
        self.BNKR_PSTN_1_Y.setObjectName("BNKR_PSTN_1_Y")
        self.gridLayout.addWidget(self.BNKR_PSTN_1_Y, 0, 2, 1, 1)
        self.SU_BSLTM_VN_Y = QtWidgets.QPushButton(self.layoutWidget1)
        self.SU_BSLTM_VN_Y.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.SU_BSLTM_VN_Y.setFont(font)
        self.SU_BSLTM_VN_Y.setObjectName("SU_BSLTM_VN_Y")
        self.gridLayout.addWidget(self.SU_BSLTM_VN_Y, 4, 3, 1, 1)
        self.KTK_BSLT_VN_Y = QtWidgets.QPushButton(self.layoutWidget1)
        self.KTK_BSLT_VN_Y.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.KTK_BSLT_VN_Y.setFont(font)
        self.KTK_BSLT_VN_Y.setObjectName("KTK_BSLT_VN_Y")
        self.gridLayout.addWidget(self.KTK_BSLT_VN_Y, 3, 3, 1, 1)
        self.SU_DLM_VN_Y = QtWidgets.QPushButton(self.layoutWidget1)
        self.SU_DLM_VN_Y.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.SU_DLM_VN_Y.setFont(font)
        self.SU_DLM_VN_Y.setObjectName("SU_DLM_VN_Y")
        self.gridLayout.addWidget(self.SU_DLM_VN_Y, 2, 3, 1, 1)
        self.CMT_BNKR_VBR_Y = QtWidgets.QPushButton(self.layoutWidget1)
        self.CMT_BNKR_VBR_Y.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.CMT_BNKR_VBR_Y.setFont(font)
        self.CMT_BNKR_VBR_Y.setObjectName("CMT_BNKR_VBR_Y")
        self.gridLayout.addWidget(self.CMT_BNKR_VBR_Y, 3, 1, 1, 1)
        self.MKSR_ANA_Y = QtWidgets.QPushButton(self.layoutWidget1)
        self.MKSR_ANA_Y.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.MKSR_ANA_Y.setFont(font)
        self.MKSR_ANA_Y.setAutoDefault(False)
        self.MKSR_ANA_Y.setDefault(False)
        self.MKSR_ANA_Y.setFlat(False)
        self.MKSR_ANA_Y.setObjectName("MKSR_ANA_Y")
        self.gridLayout.addWidget(self.MKSR_ANA_Y, 3, 0, 1, 1)
        self.BNKR_VBR_2_Y = QtWidgets.QPushButton(self.layoutWidget1)
        self.BNKR_VBR_2_Y.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BNKR_VBR_2_Y.setFont(font)
        self.BNKR_VBR_2_Y.setObjectName("BNKR_VBR_2_Y")
        self.gridLayout.addWidget(self.BNKR_VBR_2_Y, 3, 2, 1, 1)
        self.HLZN_1_Y = QtWidgets.QPushButton(self.layoutWidget1)
        self.HLZN_1_Y.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.HLZN_1_Y.setFont(font)
        self.HLZN_1_Y.setObjectName("HLZN_1_Y")
        self.gridLayout.addWidget(self.HLZN_1_Y, 4, 0, 1, 1)
        self.MKR_CKS_VB_Y = QtWidgets.QPushButton(self.layoutWidget1)
        self.MKR_CKS_VB_Y.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.MKR_CKS_VB_Y.setFont(font)
        self.MKR_CKS_VB_Y.setObjectName("MKR_CKS_VB_Y")
        self.gridLayout.addWidget(self.MKR_CKS_VB_Y, 4, 1, 1, 1)
        self.BNKR_PSTN_3_Y = QtWidgets.QPushButton(self.layoutWidget1)
        self.BNKR_PSTN_3_Y.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BNKR_PSTN_3_Y.setFont(font)
        self.BNKR_PSTN_3_Y.setObjectName("BNKR_PSTN_3_Y")
        self.gridLayout.addWidget(self.BNKR_PSTN_3_Y, 4, 2, 1, 1)
        self.HLZN_2_Y = QtWidgets.QPushButton(self.layoutWidget1)
        self.HLZN_2_Y.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.HLZN_2_Y.setFont(font)
        self.HLZN_2_Y.setObjectName("HLZN_2_Y")
        self.gridLayout.addWidget(self.HLZN_2_Y, 0, 1, 1, 1)
        self.TRTM_BND_Y = QtWidgets.QPushButton(self.layoutWidget1)
        self.TRTM_BND_Y.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TRTM_BND_Y.setFont(font)
        self.TRTM_BND_Y.setAutoDefault(False)
        self.TRTM_BND_Y.setDefault(False)
        self.TRTM_BND_Y.setFlat(False)
        self.TRTM_BND_Y.setObjectName("TRTM_BND_Y")
        self.gridLayout.addWidget(self.TRTM_BND_Y, 0, 0, 1, 1)
        self.CMNT_BSLT_VN_Y = QtWidgets.QPushButton(self.layoutWidget1)
        self.CMNT_BSLT_VN_Y.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.CMNT_BSLT_VN_Y.setFont(font)
        self.CMNT_BSLT_VN_Y.setObjectName("CMNT_BSLT_VN_Y")
        self.gridLayout.addWidget(self.CMNT_BSLT_VN_Y, 0, 4, 1, 1)
        self.TRNSFR_BND_Y = QtWidgets.QPushButton(self.layoutWidget1)
        self.TRNSFR_BND_Y.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TRNSFR_BND_Y.setFont(font)
        self.TRNSFR_BND_Y.setObjectName("TRNSFR_BND_Y")
        self.gridLayout.addWidget(self.TRNSFR_BND_Y, 1, 4, 1, 1)
        self.MKSR_PSTN_ACM_Y = QtWidgets.QPushButton(self.layoutWidget1)
        self.MKSR_PSTN_ACM_Y.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.MKSR_PSTN_ACM_Y.setFont(font)
        self.MKSR_PSTN_ACM_Y.setObjectName("MKSR_PSTN_ACM_Y")
        self.gridLayout.addWidget(self.MKSR_PSTN_ACM_Y, 2, 4, 1, 1)
        self.MKSR_PSTN_KPTM_Y = QtWidgets.QPushButton(self.layoutWidget1)
        self.MKSR_PSTN_KPTM_Y.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.MKSR_PSTN_KPTM_Y.setFont(font)
        self.MKSR_PSTN_KPTM_Y.setObjectName("MKSR_PSTN_KPTM_Y")
        self.gridLayout.addWidget(self.MKSR_PSTN_KPTM_Y, 3, 4, 1, 1)
        self.KMPRSR_Y = QtWidgets.QPushButton(self.layoutWidget1)
        self.KMPRSR_Y.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.KMPRSR_Y.setFont(font)
        self.KMPRSR_Y.setObjectName("KMPRSR_Y")
        self.gridLayout.addWidget(self.KMPRSR_Y, 4, 4, 1, 1)
        self.mod_butonu = QtWidgets.QPushButton(self.manuel_sayfasi)
        self.mod_butonu.setGeometry(QtCore.QRect(800, 20, 300, 81))
        self.mod_butonu.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.mod_butonu.setFont(font)
        self.mod_butonu.setObjectName("mod_butonu")
        self.stackedWidget.addWidget(self.manuel_sayfasi)
        self.ayarlar_sayfasi = QtWidgets.QWidget()
        self.ayarlar_sayfasi.setObjectName("ayarlar_sayfasi")
        self.label_2 = QtWidgets.QLabel(self.ayarlar_sayfasi)
        self.label_2.setGeometry(QtCore.QRect(410, 170, 481, 291))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.ayarlar_sayfasi)
        self.kalibrasyon_sayfasi = QtWidgets.QWidget()
        self.kalibrasyon_sayfasi.setObjectName("kalibrasyon_sayfasi")
        self.frame_cimento_kal = QtWidgets.QFrame(self.kalibrasyon_sayfasi)
        self.frame_cimento_kal.setGeometry(QtCore.QRect(30, 20, 891, 391))
        self.frame_cimento_kal.setStyleSheet("background-color: rgb(231, 242, 255);")
        self.frame_cimento_kal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_cimento_kal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_cimento_kal.setObjectName("frame_cimento_kal")
        self.layoutWidget2 = QtWidgets.QWidget(self.frame_cimento_kal)
        self.layoutWidget2.setGeometry(QtCore.QRect(350, 50, 541, 271))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ln_cmnt_bos_deger = QtWidgets.QLineEdit(self.layoutWidget2)
        self.ln_cmnt_bos_deger.setMaximumSize(QtCore.QSize(500, 30))
        self.ln_cmnt_bos_deger.setObjectName("ln_cmnt_bos_deger")
        self.gridLayout_2.addWidget(self.ln_cmnt_bos_deger, 1, 0, 1, 1)
        self.ln_cmnt_dolu_deger = QtWidgets.QLineEdit(self.layoutWidget2)
        self.ln_cmnt_dolu_deger.setMaximumSize(QtCore.QSize(500, 30))
        self.ln_cmnt_dolu_deger.setObjectName("ln_cmnt_dolu_deger")
        self.gridLayout_2.addWidget(self.ln_cmnt_dolu_deger, 2, 0, 1, 1)
        self.ln_cmnt_dolu_kg = QtWidgets.QLineEdit(self.layoutWidget2)
        self.ln_cmnt_dolu_kg.setMaximumSize(QtCore.QSize(500, 30))
        self.ln_cmnt_dolu_kg.setObjectName("ln_cmnt_dolu_kg")
        self.gridLayout_2.addWidget(self.ln_cmnt_dolu_kg, 4, 0, 1, 1)
        self.ln_cmnt_sonuc_kg = QtWidgets.QLineEdit(self.layoutWidget2)
        self.ln_cmnt_sonuc_kg.setMaximumSize(QtCore.QSize(500, 30))
        self.ln_cmnt_sonuc_kg.setReadOnly(True)
        self.ln_cmnt_sonuc_kg.setObjectName("ln_cmnt_sonuc_kg")
        self.gridLayout_2.addWidget(self.ln_cmnt_sonuc_kg, 5, 0, 1, 1)
        self.ln_cmnt_bos_kg = QtWidgets.QLineEdit(self.layoutWidget2)
        self.ln_cmnt_bos_kg.setMaximumSize(QtCore.QSize(500, 30))
        self.ln_cmnt_bos_kg.setObjectName("ln_cmnt_bos_kg")
        self.gridLayout_2.addWidget(self.ln_cmnt_bos_kg, 3, 0, 1, 1)
        self.ln_cmnt_ham = QtWidgets.QLineEdit(self.layoutWidget2)
        self.ln_cmnt_ham.setMaximumSize(QtCore.QSize(500, 30))
        self.ln_cmnt_ham.setReadOnly(True)
        self.ln_cmnt_ham.setObjectName("ln_cmnt_ham")
        self.gridLayout_2.addWidget(self.ln_cmnt_ham, 0, 0, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.frame_cimento_kal)
        self.layoutWidget3.setGeometry(QtCore.QRect(60, 50, 281, 271))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lb_cmnt_ham = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_cmnt_ham.setFont(font)
        self.lb_cmnt_ham.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_cmnt_ham.setTextFormat(QtCore.Qt.AutoText)
        self.lb_cmnt_ham.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_cmnt_ham.setObjectName("lb_cmnt_ham")
        self.gridLayout_3.addWidget(self.lb_cmnt_ham, 0, 0, 1, 1)
        self.lb_cmnt_bos_deger = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_cmnt_bos_deger.setFont(font)
        self.lb_cmnt_bos_deger.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_cmnt_bos_deger.setTextFormat(QtCore.Qt.AutoText)
        self.lb_cmnt_bos_deger.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_cmnt_bos_deger.setObjectName("lb_cmnt_bos_deger")
        self.gridLayout_3.addWidget(self.lb_cmnt_bos_deger, 1, 0, 1, 1)
        self.lb_cmnt_dolu_deger = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_cmnt_dolu_deger.setFont(font)
        self.lb_cmnt_dolu_deger.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_cmnt_dolu_deger.setTextFormat(QtCore.Qt.AutoText)
        self.lb_cmnt_dolu_deger.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_cmnt_dolu_deger.setObjectName("lb_cmnt_dolu_deger")
        self.gridLayout_3.addWidget(self.lb_cmnt_dolu_deger, 2, 0, 1, 1)
        self.lb_cmnt_bos_kg = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_cmnt_bos_kg.setFont(font)
        self.lb_cmnt_bos_kg.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_cmnt_bos_kg.setTextFormat(QtCore.Qt.AutoText)
        self.lb_cmnt_bos_kg.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_cmnt_bos_kg.setObjectName("lb_cmnt_bos_kg")
        self.gridLayout_3.addWidget(self.lb_cmnt_bos_kg, 3, 0, 1, 1)
        self.lb_cmnt_dolu_kg = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_cmnt_dolu_kg.setFont(font)
        self.lb_cmnt_dolu_kg.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_cmnt_dolu_kg.setTextFormat(QtCore.Qt.AutoText)
        self.lb_cmnt_dolu_kg.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_cmnt_dolu_kg.setObjectName("lb_cmnt_dolu_kg")
        self.gridLayout_3.addWidget(self.lb_cmnt_dolu_kg, 4, 0, 1, 1)
        self.lb_cmnt_sonuc_kg = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_cmnt_sonuc_kg.setFont(font)
        self.lb_cmnt_sonuc_kg.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_cmnt_sonuc_kg.setTextFormat(QtCore.Qt.AutoText)
        self.lb_cmnt_sonuc_kg.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_cmnt_sonuc_kg.setObjectName("lb_cmnt_sonuc_kg")
        self.gridLayout_3.addWidget(self.lb_cmnt_sonuc_kg, 5, 0, 1, 1)
        self.lb_cmnt_kalibrasyon_guncelle = QtWidgets.QPushButton(self.frame_cimento_kal)
        self.lb_cmnt_kalibrasyon_guncelle.setGeometry(QtCore.QRect(520, 330, 350, 51))
        self.lb_cmnt_kalibrasyon_guncelle.setMaximumSize(QtCore.QSize(500, 100))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_cmnt_kalibrasyon_guncelle.setFont(font)
        self.lb_cmnt_kalibrasyon_guncelle.setStyleSheet("background-color: rgb(178, 222, 255);")
        self.lb_cmnt_kalibrasyon_guncelle.setObjectName("lb_cmnt_kalibrasyon_guncelle")
        self.lb_cmnt_kalibrasyon_baslik = QtWidgets.QLabel(self.frame_cimento_kal)
        self.lb_cmnt_kalibrasyon_baslik.setGeometry(QtCore.QRect(200, 0, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_cmnt_kalibrasyon_baslik.setFont(font)
        self.lb_cmnt_kalibrasyon_baslik.setObjectName("lb_cmnt_kalibrasyon_baslik")
        self.lb_cmnt_kalibrasyon_deger_oku = QtWidgets.QPushButton(self.frame_cimento_kal)
        self.lb_cmnt_kalibrasyon_deger_oku.setGeometry(QtCore.QRect(60, 330, 350, 51))
        self.lb_cmnt_kalibrasyon_deger_oku.setMaximumSize(QtCore.QSize(500, 100))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_cmnt_kalibrasyon_deger_oku.setFont(font)
        self.lb_cmnt_kalibrasyon_deger_oku.setStyleSheet("background-color: rgb(178, 222, 255);")
        self.lb_cmnt_kalibrasyon_deger_oku.setObjectName("lb_cmnt_kalibrasyon_deger_oku")
        self.frame_katki_kal = QtWidgets.QFrame(self.kalibrasyon_sayfasi)
        self.frame_katki_kal.setGeometry(QtCore.QRect(990, 20, 891, 391))
        self.frame_katki_kal.setStyleSheet("background-color: rgb(231, 242, 255);")
        self.frame_katki_kal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_katki_kal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_katki_kal.setObjectName("frame_katki_kal")
        self.layoutWidget_6 = QtWidgets.QWidget(self.frame_katki_kal)
        self.layoutWidget_6.setGeometry(QtCore.QRect(350, 50, 541, 271))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget_6)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.ln_katki_bos_deger = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.ln_katki_bos_deger.setMaximumSize(QtCore.QSize(500, 30))
        self.ln_katki_bos_deger.setObjectName("ln_katki_bos_deger")
        self.gridLayout_8.addWidget(self.ln_katki_bos_deger, 1, 0, 1, 1)
        self.ln_katki_dolu_deger = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.ln_katki_dolu_deger.setMaximumSize(QtCore.QSize(500, 30))
        self.ln_katki_dolu_deger.setObjectName("ln_katki_dolu_deger")
        self.gridLayout_8.addWidget(self.ln_katki_dolu_deger, 2, 0, 1, 1)
        self.ln_katki_dolu_kg = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.ln_katki_dolu_kg.setMaximumSize(QtCore.QSize(500, 30))
        self.ln_katki_dolu_kg.setObjectName("ln_katki_dolu_kg")
        self.gridLayout_8.addWidget(self.ln_katki_dolu_kg, 4, 0, 1, 1)
        self.ln_katki_sonuc_kg = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.ln_katki_sonuc_kg.setMaximumSize(QtCore.QSize(500, 30))
        self.ln_katki_sonuc_kg.setReadOnly(True)
        self.ln_katki_sonuc_kg.setObjectName("ln_katki_sonuc_kg")
        self.gridLayout_8.addWidget(self.ln_katki_sonuc_kg, 5, 0, 1, 1)
        self.ln_katki_bos_kg = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.ln_katki_bos_kg.setMaximumSize(QtCore.QSize(500, 30))
        self.ln_katki_bos_kg.setObjectName("ln_katki_bos_kg")
        self.gridLayout_8.addWidget(self.ln_katki_bos_kg, 3, 0, 1, 1)
        self.ln_katki_ham = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.ln_katki_ham.setMaximumSize(QtCore.QSize(500, 30))
        self.ln_katki_ham.setReadOnly(True)
        self.ln_katki_ham.setObjectName("ln_katki_ham")
        self.gridLayout_8.addWidget(self.ln_katki_ham, 0, 0, 1, 1)
        self.layoutWidget_7 = QtWidgets.QWidget(self.frame_katki_kal)
        self.layoutWidget_7.setGeometry(QtCore.QRect(60, 50, 281, 271))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.layoutWidget_7)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lb_katki_ham = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_katki_ham.setFont(font)
        self.lb_katki_ham.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_katki_ham.setTextFormat(QtCore.Qt.AutoText)
        self.lb_katki_ham.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_katki_ham.setObjectName("lb_katki_ham")
        self.gridLayout_9.addWidget(self.lb_katki_ham, 0, 0, 1, 1)
        self.lb_katki_bos_deger = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_katki_bos_deger.setFont(font)
        self.lb_katki_bos_deger.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_katki_bos_deger.setTextFormat(QtCore.Qt.AutoText)
        self.lb_katki_bos_deger.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_katki_bos_deger.setObjectName("lb_katki_bos_deger")
        self.gridLayout_9.addWidget(self.lb_katki_bos_deger, 1, 0, 1, 1)
        self.lb_katki_dolu_deger = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_katki_dolu_deger.setFont(font)
        self.lb_katki_dolu_deger.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_katki_dolu_deger.setTextFormat(QtCore.Qt.AutoText)
        self.lb_katki_dolu_deger.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_katki_dolu_deger.setObjectName("lb_katki_dolu_deger")
        self.gridLayout_9.addWidget(self.lb_katki_dolu_deger, 2, 0, 1, 1)
        self.lb_katki_bos_kg = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_katki_bos_kg.setFont(font)
        self.lb_katki_bos_kg.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_katki_bos_kg.setTextFormat(QtCore.Qt.AutoText)
        self.lb_katki_bos_kg.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_katki_bos_kg.setObjectName("lb_katki_bos_kg")
        self.gridLayout_9.addWidget(self.lb_katki_bos_kg, 3, 0, 1, 1)
        self.lb_katki_dolu_kg = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_katki_dolu_kg.setFont(font)
        self.lb_katki_dolu_kg.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_katki_dolu_kg.setTextFormat(QtCore.Qt.AutoText)
        self.lb_katki_dolu_kg.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_katki_dolu_kg.setObjectName("lb_katki_dolu_kg")
        self.gridLayout_9.addWidget(self.lb_katki_dolu_kg, 4, 0, 1, 1)
        self.lb_katki_sonuc_kg = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_katki_sonuc_kg.setFont(font)
        self.lb_katki_sonuc_kg.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_katki_sonuc_kg.setTextFormat(QtCore.Qt.AutoText)
        self.lb_katki_sonuc_kg.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_katki_sonuc_kg.setObjectName("lb_katki_sonuc_kg")
        self.gridLayout_9.addWidget(self.lb_katki_sonuc_kg, 5, 0, 1, 1)
        self.lb_katki_kalibrasyon_baslik = QtWidgets.QLabel(self.frame_katki_kal)
        self.lb_katki_kalibrasyon_baslik.setGeometry(QtCore.QRect(200, 0, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_katki_kalibrasyon_baslik.setFont(font)
        self.lb_katki_kalibrasyon_baslik.setObjectName("lb_katki_kalibrasyon_baslik")
        self.lb_katki_kalibrasyon_guncelle = QtWidgets.QPushButton(self.frame_katki_kal)
        self.lb_katki_kalibrasyon_guncelle.setGeometry(QtCore.QRect(520, 330, 350, 51))
        self.lb_katki_kalibrasyon_guncelle.setMaximumSize(QtCore.QSize(500, 100))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_katki_kalibrasyon_guncelle.setFont(font)
        self.lb_katki_kalibrasyon_guncelle.setStyleSheet("background-color: rgb(178, 222, 255);")
        self.lb_katki_kalibrasyon_guncelle.setObjectName("lb_katki_kalibrasyon_guncelle")
        self.lb_katki_kalibrasyon_deger_oku = QtWidgets.QPushButton(self.frame_katki_kal)
        self.lb_katki_kalibrasyon_deger_oku.setGeometry(QtCore.QRect(60, 330, 350, 51))
        self.lb_katki_kalibrasyon_deger_oku.setMaximumSize(QtCore.QSize(500, 100))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_katki_kalibrasyon_deger_oku.setFont(font)
        self.lb_katki_kalibrasyon_deger_oku.setStyleSheet("background-color: rgb(178, 222, 255);")
        self.lb_katki_kalibrasyon_deger_oku.setObjectName("lb_katki_kalibrasyon_deger_oku")
        self.frame_su_kal = QtWidgets.QFrame(self.kalibrasyon_sayfasi)
        self.frame_su_kal.setGeometry(QtCore.QRect(30, 440, 891, 391))
        self.frame_su_kal.setStyleSheet("background-color: rgb(231, 242, 255);")
        self.frame_su_kal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_su_kal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_su_kal.setObjectName("frame_su_kal")
        self.layoutWidget_12 = QtWidgets.QWidget(self.frame_su_kal)
        self.layoutWidget_12.setGeometry(QtCore.QRect(350, 50, 541, 271))
        self.layoutWidget_12.setObjectName("layoutWidget_12")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.layoutWidget_12)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.ln_su_bos_deger = QtWidgets.QLineEdit(self.layoutWidget_12)
        self.ln_su_bos_deger.setMaximumSize(QtCore.QSize(500, 30))
        self.ln_su_bos_deger.setObjectName("ln_su_bos_deger")
        self.gridLayout_14.addWidget(self.ln_su_bos_deger, 1, 0, 1, 1)
        self.ln_su_dolu_deger = QtWidgets.QLineEdit(self.layoutWidget_12)
        self.ln_su_dolu_deger.setMaximumSize(QtCore.QSize(500, 30))
        self.ln_su_dolu_deger.setObjectName("ln_su_dolu_deger")
        self.gridLayout_14.addWidget(self.ln_su_dolu_deger, 2, 0, 1, 1)
        self.ln_su_dolu_kg = QtWidgets.QLineEdit(self.layoutWidget_12)
        self.ln_su_dolu_kg.setMaximumSize(QtCore.QSize(500, 30))
        self.ln_su_dolu_kg.setObjectName("ln_su_dolu_kg")
        self.gridLayout_14.addWidget(self.ln_su_dolu_kg, 4, 0, 1, 1)
        self.ln_su_sonuc_kg = QtWidgets.QLineEdit(self.layoutWidget_12)
        self.ln_su_sonuc_kg.setMaximumSize(QtCore.QSize(500, 30))
        self.ln_su_sonuc_kg.setReadOnly(True)
        self.ln_su_sonuc_kg.setObjectName("ln_su_sonuc_kg")
        self.gridLayout_14.addWidget(self.ln_su_sonuc_kg, 5, 0, 1, 1)
        self.ln_su_bos_kg = QtWidgets.QLineEdit(self.layoutWidget_12)
        self.ln_su_bos_kg.setMaximumSize(QtCore.QSize(500, 30))
        self.ln_su_bos_kg.setObjectName("ln_su_bos_kg")
        self.gridLayout_14.addWidget(self.ln_su_bos_kg, 3, 0, 1, 1)
        self.ln_su_ham = QtWidgets.QLineEdit(self.layoutWidget_12)
        self.ln_su_ham.setMaximumSize(QtCore.QSize(500, 30))
        self.ln_su_ham.setReadOnly(True)
        self.ln_su_ham.setObjectName("ln_su_ham")
        self.gridLayout_14.addWidget(self.ln_su_ham, 0, 0, 1, 1)
        self.layoutWidget_13 = QtWidgets.QWidget(self.frame_su_kal)
        self.layoutWidget_13.setGeometry(QtCore.QRect(60, 50, 281, 271))
        self.layoutWidget_13.setObjectName("layoutWidget_13")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.layoutWidget_13)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.lb_su_ham = QtWidgets.QLabel(self.layoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_su_ham.setFont(font)
        self.lb_su_ham.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_su_ham.setTextFormat(QtCore.Qt.AutoText)
        self.lb_su_ham.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_su_ham.setObjectName("lb_su_ham")
        self.gridLayout_15.addWidget(self.lb_su_ham, 0, 0, 1, 1)
        self.lb_su_bos_deger = QtWidgets.QLabel(self.layoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_su_bos_deger.setFont(font)
        self.lb_su_bos_deger.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_su_bos_deger.setTextFormat(QtCore.Qt.AutoText)
        self.lb_su_bos_deger.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_su_bos_deger.setObjectName("lb_su_bos_deger")
        self.gridLayout_15.addWidget(self.lb_su_bos_deger, 1, 0, 1, 1)
        self.lb_su_dolu_deger = QtWidgets.QLabel(self.layoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_su_dolu_deger.setFont(font)
        self.lb_su_dolu_deger.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_su_dolu_deger.setTextFormat(QtCore.Qt.AutoText)
        self.lb_su_dolu_deger.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_su_dolu_deger.setObjectName("lb_su_dolu_deger")
        self.gridLayout_15.addWidget(self.lb_su_dolu_deger, 2, 0, 1, 1)
        self.lb_su_bos_kg = QtWidgets.QLabel(self.layoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_su_bos_kg.setFont(font)
        self.lb_su_bos_kg.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_su_bos_kg.setTextFormat(QtCore.Qt.AutoText)
        self.lb_su_bos_kg.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_su_bos_kg.setObjectName("lb_su_bos_kg")
        self.gridLayout_15.addWidget(self.lb_su_bos_kg, 3, 0, 1, 1)
        self.lb_su_dolu_kg = QtWidgets.QLabel(self.layoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_su_dolu_kg.setFont(font)
        self.lb_su_dolu_kg.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_su_dolu_kg.setTextFormat(QtCore.Qt.AutoText)
        self.lb_su_dolu_kg.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_su_dolu_kg.setObjectName("lb_su_dolu_kg")
        self.gridLayout_15.addWidget(self.lb_su_dolu_kg, 4, 0, 1, 1)
        self.lb_su_sonuc_kg = QtWidgets.QLabel(self.layoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_su_sonuc_kg.setFont(font)
        self.lb_su_sonuc_kg.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_su_sonuc_kg.setTextFormat(QtCore.Qt.AutoText)
        self.lb_su_sonuc_kg.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_su_sonuc_kg.setObjectName("lb_su_sonuc_kg")
        self.gridLayout_15.addWidget(self.lb_su_sonuc_kg, 5, 0, 1, 1)
        self.lb_su_kalibrasyon_baslik = QtWidgets.QLabel(self.frame_su_kal)
        self.lb_su_kalibrasyon_baslik.setGeometry(QtCore.QRect(200, 0, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_su_kalibrasyon_baslik.setFont(font)
        self.lb_su_kalibrasyon_baslik.setObjectName("lb_su_kalibrasyon_baslik")
        self.lb_su_kalibrasyon_guncelle = QtWidgets.QPushButton(self.frame_su_kal)
        self.lb_su_kalibrasyon_guncelle.setGeometry(QtCore.QRect(480, 330, 350, 51))
        self.lb_su_kalibrasyon_guncelle.setMaximumSize(QtCore.QSize(350, 100))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_su_kalibrasyon_guncelle.setFont(font)
        self.lb_su_kalibrasyon_guncelle.setStyleSheet("background-color: rgb(178, 222, 255);")
        self.lb_su_kalibrasyon_guncelle.setObjectName("lb_su_kalibrasyon_guncelle")
        self.lb_su_kalibrasyon_deger_oku = QtWidgets.QPushButton(self.frame_su_kal)
        self.lb_su_kalibrasyon_deger_oku.setGeometry(QtCore.QRect(60, 330, 350, 51))
        self.lb_su_kalibrasyon_deger_oku.setMaximumSize(QtCore.QSize(350, 100))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_su_kalibrasyon_deger_oku.setFont(font)
        self.lb_su_kalibrasyon_deger_oku.setStyleSheet("background-color: rgb(178, 222, 255);")
        self.lb_su_kalibrasyon_deger_oku.setObjectName("lb_su_kalibrasyon_deger_oku")
        self.frame_tartim_bandi_kal = QtWidgets.QFrame(self.kalibrasyon_sayfasi)
        self.frame_tartim_bandi_kal.setGeometry(QtCore.QRect(990, 440, 891, 391))
        self.frame_tartim_bandi_kal.setStyleSheet("background-color: rgb(231, 242, 255);")
        self.frame_tartim_bandi_kal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_tartim_bandi_kal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tartim_bandi_kal.setObjectName("frame_tartim_bandi_kal")
        self.layoutWidget_14 = QtWidgets.QWidget(self.frame_tartim_bandi_kal)
        self.layoutWidget_14.setGeometry(QtCore.QRect(350, 50, 541, 271))
        self.layoutWidget_14.setObjectName("layoutWidget_14")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.layoutWidget_14)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.ln_tartim_bandi_bos_deger = QtWidgets.QLineEdit(self.layoutWidget_14)
        self.ln_tartim_bandi_bos_deger.setMaximumSize(QtCore.QSize(500, 30))
        self.ln_tartim_bandi_bos_deger.setObjectName("ln_tartim_bandi_bos_deger")
        self.gridLayout_16.addWidget(self.ln_tartim_bandi_bos_deger, 1, 0, 1, 1)
        self.ln_tartim_bandi_dolu_deger = QtWidgets.QLineEdit(self.layoutWidget_14)
        self.ln_tartim_bandi_dolu_deger.setMaximumSize(QtCore.QSize(500, 30))
        self.ln_tartim_bandi_dolu_deger.setObjectName("ln_tartim_bandi_dolu_deger")
        self.gridLayout_16.addWidget(self.ln_tartim_bandi_dolu_deger, 2, 0, 1, 1)
        self.ln_tartim_bandi_dolu_kg = QtWidgets.QLineEdit(self.layoutWidget_14)
        self.ln_tartim_bandi_dolu_kg.setMaximumSize(QtCore.QSize(500, 30))
        self.ln_tartim_bandi_dolu_kg.setObjectName("ln_tartim_bandi_dolu_kg")
        self.gridLayout_16.addWidget(self.ln_tartim_bandi_dolu_kg, 4, 0, 1, 1)
        self.ln_tartim_bandi_sonuc_kg = QtWidgets.QLineEdit(self.layoutWidget_14)
        self.ln_tartim_bandi_sonuc_kg.setMaximumSize(QtCore.QSize(500, 30))
        self.ln_tartim_bandi_sonuc_kg.setReadOnly(True)
        self.ln_tartim_bandi_sonuc_kg.setObjectName("ln_tartim_bandi_sonuc_kg")
        self.gridLayout_16.addWidget(self.ln_tartim_bandi_sonuc_kg, 5, 0, 1, 1)
        self.ln_tartim_bandi_bos_kg = QtWidgets.QLineEdit(self.layoutWidget_14)
        self.ln_tartim_bandi_bos_kg.setMaximumSize(QtCore.QSize(500, 30))
        self.ln_tartim_bandi_bos_kg.setObjectName("ln_tartim_bandi_bos_kg")
        self.gridLayout_16.addWidget(self.ln_tartim_bandi_bos_kg, 3, 0, 1, 1)
        self.ln_tartim_bandi_ham = QtWidgets.QLineEdit(self.layoutWidget_14)
        self.ln_tartim_bandi_ham.setMaximumSize(QtCore.QSize(500, 30))
        self.ln_tartim_bandi_ham.setReadOnly(True)
        self.ln_tartim_bandi_ham.setObjectName("ln_tartim_bandi_ham")
        self.gridLayout_16.addWidget(self.ln_tartim_bandi_ham, 0, 0, 1, 1)
        self.layoutWidget_15 = QtWidgets.QWidget(self.frame_tartim_bandi_kal)
        self.layoutWidget_15.setGeometry(QtCore.QRect(60, 50, 281, 271))
        self.layoutWidget_15.setObjectName("layoutWidget_15")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.layoutWidget_15)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.lb_tartim_bandi_ham = QtWidgets.QLabel(self.layoutWidget_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_tartim_bandi_ham.setFont(font)
        self.lb_tartim_bandi_ham.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_tartim_bandi_ham.setTextFormat(QtCore.Qt.AutoText)
        self.lb_tartim_bandi_ham.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_tartim_bandi_ham.setObjectName("lb_tartim_bandi_ham")
        self.gridLayout_17.addWidget(self.lb_tartim_bandi_ham, 0, 0, 1, 1)
        self.lb_tartim_bandi_bos_deger = QtWidgets.QLabel(self.layoutWidget_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_tartim_bandi_bos_deger.setFont(font)
        self.lb_tartim_bandi_bos_deger.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_tartim_bandi_bos_deger.setTextFormat(QtCore.Qt.AutoText)
        self.lb_tartim_bandi_bos_deger.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_tartim_bandi_bos_deger.setObjectName("lb_tartim_bandi_bos_deger")
        self.gridLayout_17.addWidget(self.lb_tartim_bandi_bos_deger, 1, 0, 1, 1)
        self.lb_tartim_bandi_dolu_deger = QtWidgets.QLabel(self.layoutWidget_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_tartim_bandi_dolu_deger.setFont(font)
        self.lb_tartim_bandi_dolu_deger.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_tartim_bandi_dolu_deger.setTextFormat(QtCore.Qt.AutoText)
        self.lb_tartim_bandi_dolu_deger.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_tartim_bandi_dolu_deger.setObjectName("lb_tartim_bandi_dolu_deger")
        self.gridLayout_17.addWidget(self.lb_tartim_bandi_dolu_deger, 2, 0, 1, 1)
        self.lb_tartim_bandi_bos_kg = QtWidgets.QLabel(self.layoutWidget_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_tartim_bandi_bos_kg.setFont(font)
        self.lb_tartim_bandi_bos_kg.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_tartim_bandi_bos_kg.setTextFormat(QtCore.Qt.AutoText)
        self.lb_tartim_bandi_bos_kg.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_tartim_bandi_bos_kg.setObjectName("lb_tartim_bandi_bos_kg")
        self.gridLayout_17.addWidget(self.lb_tartim_bandi_bos_kg, 3, 0, 1, 1)
        self.lb_tartim_bandi_dolu_kg = QtWidgets.QLabel(self.layoutWidget_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_tartim_bandi_dolu_kg.setFont(font)
        self.lb_tartim_bandi_dolu_kg.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_tartim_bandi_dolu_kg.setTextFormat(QtCore.Qt.AutoText)
        self.lb_tartim_bandi_dolu_kg.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_tartim_bandi_dolu_kg.setObjectName("lb_tartim_bandi_dolu_kg")
        self.gridLayout_17.addWidget(self.lb_tartim_bandi_dolu_kg, 4, 0, 1, 1)
        self.lb_tartim_bandi_sonuc_kg = QtWidgets.QLabel(self.layoutWidget_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_tartim_bandi_sonuc_kg.setFont(font)
        self.lb_tartim_bandi_sonuc_kg.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_tartim_bandi_sonuc_kg.setTextFormat(QtCore.Qt.AutoText)
        self.lb_tartim_bandi_sonuc_kg.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_tartim_bandi_sonuc_kg.setObjectName("lb_tartim_bandi_sonuc_kg")
        self.gridLayout_17.addWidget(self.lb_tartim_bandi_sonuc_kg, 5, 0, 1, 1)
        self.lb_tartim_bandi_kalibrasyon_baslik = QtWidgets.QLabel(self.frame_tartim_bandi_kal)
        self.lb_tartim_bandi_kalibrasyon_baslik.setGeometry(QtCore.QRect(200, 0, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_tartim_bandi_kalibrasyon_baslik.setFont(font)
        self.lb_tartim_bandi_kalibrasyon_baslik.setObjectName("lb_tartim_bandi_kalibrasyon_baslik")
        self.lb_tartim_bandi_kalibrasyon_guncelle = QtWidgets.QPushButton(self.frame_tartim_bandi_kal)
        self.lb_tartim_bandi_kalibrasyon_guncelle.setGeometry(QtCore.QRect(520, 330, 350, 51))
        self.lb_tartim_bandi_kalibrasyon_guncelle.setMaximumSize(QtCore.QSize(350, 100))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_tartim_bandi_kalibrasyon_guncelle.setFont(font)
        self.lb_tartim_bandi_kalibrasyon_guncelle.setStyleSheet("background-color: rgb(178, 222, 255);")
        self.lb_tartim_bandi_kalibrasyon_guncelle.setObjectName("lb_tartim_bandi_kalibrasyon_guncelle")
        self.lb_tartim_bandi_kalibrasyon_deger_oku = QtWidgets.QPushButton(self.frame_tartim_bandi_kal)
        self.lb_tartim_bandi_kalibrasyon_deger_oku.setGeometry(QtCore.QRect(60, 330, 350, 51))
        self.lb_tartim_bandi_kalibrasyon_deger_oku.setMaximumSize(QtCore.QSize(350, 100))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lb_tartim_bandi_kalibrasyon_deger_oku.setFont(font)
        self.lb_tartim_bandi_kalibrasyon_deger_oku.setStyleSheet("background-color: rgb(178, 222, 255);")
        self.lb_tartim_bandi_kalibrasyon_deger_oku.setObjectName("lb_tartim_bandi_kalibrasyon_deger_oku")
        self.stackedWidget.addWidget(self.kalibrasyon_sayfasi)
        self.recete_sayfasi = QtWidgets.QWidget()
        self.recete_sayfasi.setObjectName("recete_sayfasi")
        self.frame = QtWidgets.QFrame(self.recete_sayfasi)
        self.frame.setGeometry(QtCore.QRect(1060, 30, 801, 811))
        self.frame.setStyleSheet("background-color: rgb(192, 201, 212);")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.vt_kaydet = QtWidgets.QPushButton(self.frame)
        self.vt_kaydet.setGeometry(QtCore.QRect(220, 610, 420, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.vt_kaydet.setFont(font)
        self.vt_kaydet.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.vt_kaydet.setObjectName("vt_kaydet")
        self.lb_recete_oranlar = QtWidgets.QLabel(self.frame)
        self.lb_recete_oranlar.setGeometry(QtCore.QRect(190, 20, 421, 51))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.lb_recete_oranlar.setFont(font)
        self.lb_recete_oranlar.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_recete_oranlar.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_recete_oranlar.setObjectName("lb_recete_oranlar")
        self.layoutWidget_16 = QtWidgets.QWidget(self.frame)
        self.layoutWidget_16.setGeometry(QtCore.QRect(370, 110, 421, 431))
        self.layoutWidget_16.setObjectName("layoutWidget_16")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_16)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ln_recete_no = QtWidgets.QLineEdit(self.layoutWidget_16)
        self.ln_recete_no.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_recete_no.sizePolicy().hasHeightForWidth())
        self.ln_recete_no.setSizePolicy(sizePolicy)
        self.ln_recete_no.setStyleSheet("background-color: rgb(217, 219, 255);")
        self.ln_recete_no.setObjectName("ln_recete_no")
        self.verticalLayout_5.addWidget(self.ln_recete_no)
        self.ln_recete_adi = QtWidgets.QLineEdit(self.layoutWidget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_recete_adi.sizePolicy().hasHeightForWidth())
        self.ln_recete_adi.setSizePolicy(sizePolicy)
        self.ln_recete_adi.setStyleSheet("background-color: rgb(217, 219, 255);")
        self.ln_recete_adi.setObjectName("ln_recete_adi")
        self.verticalLayout_5.addWidget(self.ln_recete_adi)
        self.ln_kum_1 = QtWidgets.QLineEdit(self.layoutWidget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_kum_1.sizePolicy().hasHeightForWidth())
        self.ln_kum_1.setSizePolicy(sizePolicy)
        self.ln_kum_1.setStyleSheet("background-color: rgb(217, 219, 255);")
        self.ln_kum_1.setObjectName("ln_kum_1")
        self.verticalLayout_5.addWidget(self.ln_kum_1)
        self.ln_kum_2 = QtWidgets.QLineEdit(self.layoutWidget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_kum_2.sizePolicy().hasHeightForWidth())
        self.ln_kum_2.setSizePolicy(sizePolicy)
        self.ln_kum_2.setStyleSheet("background-color: rgb(217, 219, 255);")
        self.ln_kum_2.setObjectName("ln_kum_2")
        self.verticalLayout_5.addWidget(self.ln_kum_2)
        self.ln_kum_3 = QtWidgets.QLineEdit(self.layoutWidget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_kum_3.sizePolicy().hasHeightForWidth())
        self.ln_kum_3.setSizePolicy(sizePolicy)
        self.ln_kum_3.setStyleSheet("background-color: rgb(217, 219, 255);")
        self.ln_kum_3.setObjectName("ln_kum_3")
        self.verticalLayout_5.addWidget(self.ln_kum_3)
        self.ln_cimento = QtWidgets.QLineEdit(self.layoutWidget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_cimento.sizePolicy().hasHeightForWidth())
        self.ln_cimento.setSizePolicy(sizePolicy)
        self.ln_cimento.setStyleSheet("background-color: rgb(217, 219, 255);")
        self.ln_cimento.setObjectName("ln_cimento")
        self.verticalLayout_5.addWidget(self.ln_cimento)
        self.ln_su = QtWidgets.QLineEdit(self.layoutWidget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_su.sizePolicy().hasHeightForWidth())
        self.ln_su.setSizePolicy(sizePolicy)
        self.ln_su.setStyleSheet("background-color: rgb(217, 219, 255);")
        self.ln_su.setObjectName("ln_su")
        self.verticalLayout_5.addWidget(self.ln_su)
        self.ln_katki = QtWidgets.QLineEdit(self.layoutWidget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_katki.sizePolicy().hasHeightForWidth())
        self.ln_katki.setSizePolicy(sizePolicy)
        self.ln_katki.setStyleSheet("background-color: rgb(217, 219, 255);")
        self.ln_katki.setObjectName("ln_katki")
        self.verticalLayout_5.addWidget(self.ln_katki)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(30, 110, 301, 431))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.verticalLayoutWidget_4.setFont(font)
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lb_recete_no = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.lb_recete_no.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(27)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lb_recete_no.setFont(font)
        self.lb_recete_no.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"background-color: rgb(189, 189, 189);")
        self.lb_recete_no.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lb_recete_no.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lb_recete_no.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_recete_no.setObjectName("lb_recete_no")
        self.verticalLayout_6.addWidget(self.lb_recete_no)
        self.lb_recete_adi = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.lb_recete_adi.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(27)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lb_recete_adi.setFont(font)
        self.lb_recete_adi.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"background-color: rgb(189, 189, 189);")
        self.lb_recete_adi.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lb_recete_adi.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lb_recete_adi.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_recete_adi.setObjectName("lb_recete_adi")
        self.verticalLayout_6.addWidget(self.lb_recete_adi)
        self.lb_kum_1 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(27)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lb_kum_1.setFont(font)
        self.lb_kum_1.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"background-color: rgb(189, 189, 189);")
        self.lb_kum_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lb_kum_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lb_kum_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_kum_1.setObjectName("lb_kum_1")
        self.verticalLayout_6.addWidget(self.lb_kum_1)
        self.lb_kum_2 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(27)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lb_kum_2.setFont(font)
        self.lb_kum_2.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"background-color: rgb(189, 189, 189);")
        self.lb_kum_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lb_kum_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lb_kum_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_kum_2.setObjectName("lb_kum_2")
        self.verticalLayout_6.addWidget(self.lb_kum_2)
        self.lb_kum_3 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(27)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lb_kum_3.setFont(font)
        self.lb_kum_3.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"background-color: rgb(189, 189, 189);")
        self.lb_kum_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lb_kum_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lb_kum_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_kum_3.setObjectName("lb_kum_3")
        self.verticalLayout_6.addWidget(self.lb_kum_3)
        self.lb_cimento = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(27)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lb_cimento.setFont(font)
        self.lb_cimento.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"background-color: rgb(189, 189, 189);")
        self.lb_cimento.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lb_cimento.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lb_cimento.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_cimento.setObjectName("lb_cimento")
        self.verticalLayout_6.addWidget(self.lb_cimento)
        self.lb_su = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lb_su.setFont(font)
        self.lb_su.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"background-color: rgb(189, 189, 189);")
        self.lb_su.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lb_su.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lb_su.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_su.setObjectName("lb_su")
        self.verticalLayout_6.addWidget(self.lb_su)
        self.lb_katki = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(27)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lb_katki.setFont(font)
        self.lb_katki.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"background-color: rgb(189, 189, 189);")
        self.lb_katki.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lb_katki.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lb_katki.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_katki.setObjectName("lb_katki")
        self.verticalLayout_6.addWidget(self.lb_katki)
        self.frame_2 = QtWidgets.QFrame(self.recete_sayfasi)
        self.frame_2.setGeometry(QtCore.QRect(30, 30, 951, 811))
        self.frame_2.setStyleSheet("background-color: rgb(192, 201, 212);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lb_recete_baslik = QtWidgets.QLabel(self.frame_2)
        self.lb_recete_baslik.setGeometry(QtCore.QRect(250, 20, 421, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.lb_recete_baslik.setFont(font)
        self.lb_recete_baslik.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_recete_baslik.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_recete_baslik.setObjectName("lb_recete_baslik")
        self.recete_gonder = QtWidgets.QPushButton(self.frame_2)
        self.recete_gonder.setGeometry(QtCore.QRect(650, 730, 250, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.recete_gonder.setFont(font)
        self.recete_gonder.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.recete_gonder.setObjectName("recete_gonder")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_2)
        self.tableWidget.setGeometry(QtCore.QRect(50, 80, 851, 631))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setRowCount(20)
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setObjectName("tableWidget")
        self.vt_sil = QtWidgets.QPushButton(self.frame_2)
        self.vt_sil.setGeometry(QtCore.QRect(50, 730, 250, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.vt_sil.setFont(font)
        self.vt_sil.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.vt_sil.setObjectName("vt_sil")
        self.vt_guncelle = QtWidgets.QPushButton(self.frame_2)
        self.vt_guncelle.setGeometry(QtCore.QRect(350, 730, 250, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.vt_guncelle.setFont(font)
        self.vt_guncelle.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.vt_guncelle.setObjectName("vt_guncelle")
        self.stackedWidget.addWidget(self.recete_sayfasi)
        self.lb_date = QtWidgets.QLabel(self.centralwidget)
        self.lb_date.setGeometry(QtCore.QRect(1710, 0, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lb_date.setFont(font)
        self.lb_date.setObjectName("lb_date")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1915, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.manuel_menu.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.manuel_sayfasi))
        self.uretim_menu.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.uretim_sayfasi))
        self.kalibrasyon_menu.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.kalibrasyon_sayfasi))
        self.ayarlar_menu.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.ayarlar_sayfasi))
        self.recete_menu.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.recete_sayfasi))        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)            

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.uretim_menu.setText(_translate("MainWindow", "ÜRETİM SAYFASI"))
        self.manuel_menu.setText(_translate("MainWindow", "MANUEL"))
        self.ayarlar_menu.setText(_translate("MainWindow", "AYARLAR"))
        self.kalibrasyon_menu.setText(_translate("MainWindow", "KALİBRASYON"))
        self.recete_menu.setText(_translate("MainWindow", "REÇETE"))
        self.proses_baslat_button.setText(_translate("MainWindow", "PROSES BAŞLAT"))
        self.acil_stop_button.setText(_translate("MainWindow", "ACİL STOP"))
        self.mikser_manuel_bosalt_button.setText(_translate("MainWindow", "MİKSER MANUEL BOŞALT"))
        self.cimento_tartim_bosalt.setText(_translate("MainWindow", "ÇİMENTO TARTIM BOŞALT"))
        self.katki_tartim_bosalt.setText(_translate("MainWindow", "KATKI TARTIM BOŞALT"))
        self.su_tartim_bosalt.setText(_translate("MainWindow", "SU TARTIM BOŞALT"))
        self.tartim_bandi_bosalt.setText(_translate("MainWindow", " TARTIM BANDI BOŞALT"))
        self.lb_recete_baslik_2.setText(_translate("MainWindow", "SEÇİLİ REÇETE"))
        self.mikser_bosaltma_piston_g.setText(_translate("MainWindow", "MİKSER BOŞALTMA\n"
" PİSTONU"))
        self.kum_1_vibro_g.setText(_translate("MainWindow", "KUM-1 VİBRO"))
        self.kum_2_vibro_g.setText(_translate("MainWindow", "KUM-2 VİBRO"))
        self.kum_3_vibro_g.setText(_translate("MainWindow", "KUM-3 VİBRO"))
        self.tartim_bandi_motor_g.setText(_translate("MainWindow", "TARTIM BANDI\n"
" MOTORU"))
        self.tartim_bandi_akt_mt_g.setText(_translate("MainWindow", "TARTIM BANDI\n"
" AKTARMA MOTORU"))
        self.kum_3_piston_g.setText(_translate("MainWindow", "KUM-3 PİSTON"))
        self.kum_1_piston_g.setText(_translate("MainWindow", "KUM-1 PİSTON"))
        self.kum_2_piston_g.setText(_translate("MainWindow", "KUM-2 PİSTON"))
        self.su_pompasi_g.setText(_translate("MainWindow", "SU POMPASI"))
        self.katki_pompasi_g.setText(_translate("MainWindow", "KATKI POMPASI"))
        self.cimento_akt_hlz_mt_g.setText(_translate("MainWindow", "CİMENTO AKTARMA\n"
"HELEZONU"))
        self.mikser_motoru_g.setText(_translate("MainWindow", "MİKSER MOTORU"))
        self.mikser_bosaltma_vibro_g.setText(_translate("MainWindow", "MİKSER BOŞALTMA\n"
" VİBRO"))
        self.HDRLK_MTR_Y.setText(_translate("MainWindow", "HİDROLİK MOTOR"))
        self.SRN_Y.setText(_translate("MainWindow", "SİREN"))
        self.BNKR_VBR_1_Y.setText(_translate("MainWindow", "BUNKER VİBRATÖRÜ - 1"))
        self.KTK_PMP_2_Y.setText(_translate("MainWindow", "KATKI POMPASI - 2"))
        self.BNKR_PSTN_2_Y.setText(_translate("MainWindow", "BUNKER PİSTON - 2"))
        self.TRTM_VBR_Y.setText(_translate("MainWindow", "TARTIM VİBRATÖRÜ"))
        self.KTK_PMP_1_Y.setText(_translate("MainWindow", "KATKI POMPASI - 1"))
        self.BNKR_VBR_3_Y.setText(_translate("MainWindow", "BUNKER VİBRATÖRÜ - 3"))
        self.BNKR_PSTN_1_Y.setText(_translate("MainWindow", "BUNKER PİSTON - 1"))
        self.SU_BSLTM_VN_Y.setText(_translate("MainWindow", "SU BOŞALTMA VANASI"))
        self.KTK_BSLT_VN_Y.setText(_translate("MainWindow", "KATKI BOŞALTMA VANASI"))
        self.SU_DLM_VN_Y.setText(_translate("MainWindow", "SU DOLUM VANASI"))
        self.CMT_BNKR_VBR_Y.setText(_translate("MainWindow", "ÇİMENTO BUNKER VİBRATÖRÜ"))
        self.MKSR_ANA_Y.setText(_translate("MainWindow", "MİKSER"))
        self.BNKR_VBR_2_Y.setText(_translate("MainWindow", "BUNKER VİBRATÖRÜ - 2"))
        self.HLZN_1_Y.setText(_translate("MainWindow", "HELEZON - 1"))
        self.MKR_CKS_VB_Y.setText(_translate("MainWindow", "MİKSER ÇIKIŞ VİBRATÖRÜ"))
        self.BNKR_PSTN_3_Y.setText(_translate("MainWindow", "BUNKER PİSTON - 3"))
        self.HLZN_2_Y.setText(_translate("MainWindow", "HELEZON-2"))
        self.TRTM_BND_Y.setText(_translate("MainWindow", "TARTIM BANDI"))
        self.CMNT_BSLT_VN_Y.setText(_translate("MainWindow", "ÇİMENTO BOŞALTMA VANASI"))
        self.TRNSFR_BND_Y.setText(_translate("MainWindow", "TRANSFER BANDI"))
        self.MKSR_PSTN_ACM_Y.setText(_translate("MainWindow", "MİKSER PİSTON AÇ"))
        self.MKSR_PSTN_KPTM_Y.setText(_translate("MainWindow", "MİKSER PİSTON KAPAT"))
        self.KMPRSR_Y.setText(_translate("MainWindow", "KOMPRESÖR"))
        self.mod_butonu.setText(_translate("MainWindow", "MANUEL MOD"))
        self.label_2.setText(_translate("MainWindow", "AYARLAR SAYFASI"))
        self.lb_cmnt_ham.setText(_translate("MainWindow", "ÇİMENTO OKUNAN DEĞER"))
        self.lb_cmnt_bos_deger.setText(_translate("MainWindow", "ÇİMENTO BOŞ DEĞER"))
        self.lb_cmnt_dolu_deger.setText(_translate("MainWindow", "ÇİMENTO DOLU DEĞER"))
        self.lb_cmnt_bos_kg.setText(_translate("MainWindow", "ÇİMENTO BOŞ KG"))
        self.lb_cmnt_dolu_kg.setText(_translate("MainWindow", "ÇİMENTO DOLU KG"))
        self.lb_cmnt_sonuc_kg.setText(_translate("MainWindow", "ÇİMENTO SONUÇ KG"))
        self.lb_cmnt_kalibrasyon_guncelle.setText(_translate("MainWindow", "ÇİMENTO KALİBRASYON GÜNCELLE"))
        self.lb_cmnt_kalibrasyon_baslik.setText(_translate("MainWindow", "ÇİMENTO TARTIM KALİBRASYONU"))
        self.lb_cmnt_kalibrasyon_deger_oku.setText(_translate("MainWindow", "ÇİMENTO KALİBRASYON DEĞER ÇAĞIR"))
        self.lb_katki_ham.setText(_translate("MainWindow", "KATKI  OKUNAN DEĞER"))
        self.lb_katki_bos_deger.setText(_translate("MainWindow", "KATKI  BOŞ DEĞER"))
        self.lb_katki_dolu_deger.setText(_translate("MainWindow", "KATKI  DOLU DEĞER"))
        self.lb_katki_bos_kg.setText(_translate("MainWindow", "KATKI  BOŞ KG"))
        self.lb_katki_dolu_kg.setText(_translate("MainWindow", "KATKI  DOLU KG"))
        self.lb_katki_sonuc_kg.setText(_translate("MainWindow", "KATKI  SONUÇ KG"))
        self.lb_katki_kalibrasyon_baslik.setText(_translate("MainWindow", "KATKI TARTIM KALİBRASYONU"))
        self.lb_katki_kalibrasyon_guncelle.setText(_translate("MainWindow", "KATKI  KALİBRASYON GÜNCELLE"))
        self.lb_katki_kalibrasyon_deger_oku.setText(_translate("MainWindow", "KATKI  KALİBRASYON DEĞER ÇAĞIR"))
        self.lb_su_ham.setText(_translate("MainWindow", "SU OKUNAN DEĞER"))
        self.lb_su_bos_deger.setText(_translate("MainWindow", "SU BOŞ DEĞER"))
        self.lb_su_dolu_deger.setText(_translate("MainWindow", "SU DOLU DEĞER"))
        self.lb_su_bos_kg.setText(_translate("MainWindow", "SU BOŞ KG"))
        self.lb_su_dolu_kg.setText(_translate("MainWindow", "SU DOLU KG"))
        self.lb_su_sonuc_kg.setText(_translate("MainWindow", "SU SONUÇ KG"))
        self.lb_su_kalibrasyon_baslik.setText(_translate("MainWindow", "SU TARTIM KALİBRASYONU"))
        self.lb_su_kalibrasyon_guncelle.setText(_translate("MainWindow", "SU KALİBRASYON GÜNCELLE"))
        self.lb_su_kalibrasyon_deger_oku.setText(_translate("MainWindow", "SU KALİBRASYON DEĞER ÇAĞIR"))
        self.lb_tartim_bandi_ham.setText(_translate("MainWindow", "TARTIM BANDI OKUNAN DEĞER"))
        self.lb_tartim_bandi_bos_deger.setText(_translate("MainWindow", "TARTIM BANDI BOŞ DEĞER"))
        self.lb_tartim_bandi_dolu_deger.setText(_translate("MainWindow", "TARTIM BANDI DOLU DEĞER"))
        self.lb_tartim_bandi_bos_kg.setText(_translate("MainWindow", "TARTIM BANDI BOŞ KG"))
        self.lb_tartim_bandi_dolu_kg.setText(_translate("MainWindow", "TARTIM BANDI DOLU KG"))
        self.lb_tartim_bandi_sonuc_kg.setText(_translate("MainWindow", "TARTIM BANDI SONUÇ KG"))
        self.lb_tartim_bandi_kalibrasyon_baslik.setText(_translate("MainWindow", "TARTIM BANDI TARTIM KALİBRASYONU"))
        self.lb_tartim_bandi_kalibrasyon_guncelle.setText(_translate("MainWindow", "TARTIM BANDI KALİBRASYON GÜNCELLE"))
        self.lb_tartim_bandi_kalibrasyon_deger_oku.setText(_translate("MainWindow", "TARTIM BANDI KALİBRASYON DEĞER ÇAĞIR"))
        self.vt_kaydet.setText(_translate("MainWindow", "Kaydet"))
        self.lb_recete_oranlar.setText(_translate("MainWindow", "REÇETE ORANLARI"))
        self.verticalLayoutWidget_4.setStyleSheet(_translate("MainWindow", "gridline-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"gridline-color: rgb(0, 0, 0);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-color: rgb(255, 0, 0);"))
        self.lb_recete_no.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Reçete No</span></p></body></html>"))
        self.lb_recete_adi.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Reçete Adı:</span></p></body></html>"))
        self.lb_kum_1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Kum - 1</span></p></body></html>"))
        self.lb_kum_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Kum - 2</span></p></body></html>"))
        self.lb_kum_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Kum - 3</span></p></body></html>"))
        self.lb_cimento.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Çimento </span></p></body></html>"))
        self.lb_su.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Su</span></p></body></html>"))
        self.lb_katki.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Katkı</span></p></body></html>"))
        self.lb_recete_baslik.setText(_translate("MainWindow", "KAYITLI REÇETELER"))
        self.recete_gonder.setText(_translate("MainWindow", "Gönder"))
        self.vt_sil.setText(_translate("MainWindow", "Sil"))
        self.vt_guncelle.setText(_translate("MainWindow", "Güncelle"))
        self.lb_date.setText(_translate("MainWindow", "TextLabel"))

import kaynaklar_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

